category-template: '### $TITLE'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title: '📖 Documentation'
    label: 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
  - 'automation'
template: |
  Changes in this release:
  $CHANGES
autolabeler:
  - label: 'maintenance'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    files: 'Sources/Orbit/Components/**/*'
  - label: 'automation'
    files:
      - 'Automation/**/*'
      - '.github/**/*'
  - label: 'documentation'
    files: 'Sources/Orbit/Orbit.docc/**/*'