name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: set -o pipefail && xcodebuild -scheme Orbit -destination "generic/platform=iOS Simulator" | xcpretty
  check-components-have-snapshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check components have snapshots
      run: Automation/check_components_have_snapshot_tests.sh
  test:
    needs: check-components-have-snapshots
    strategy:
      matrix:
        device: ["iPhone 13", "iPhone SE (1st generation)", "iPad (9th generation)"]
        os_version: ["15.5"]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        id=$(Automation/get_simulator.py "${{ matrix.device }}" "${{ matrix.os_version }}")
        set -o pipefail && xcodebuild test -scheme Orbit-Package -destination "platform=iOS Simulator,id=$id,OS=${{ matrix.os_version }}" | xcpretty
