name: Regenerate Snapshots

on:
  workflow_dispatch:

jobs:
  generate_snapshots:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SNAPSHOT_PUSH_TOKEN }}
      - name: generate
        run: |
          Automation/regenerate_snapshots.sh
      - name: upload
        run: |
            git config --global user.name "Mobile Automation"
            git config --global user.email "mobile.automation@kiwi.com"
            git commit -m "Updated snapshots." || true
            git push
