name: Snapshot Updater

on:
  workflow_dispatch:

jobs:
  generate_snapshots:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SNAPSHOT_PUSH_TOKEN }}
      - name: generate
        run: |
          Automation/generate_snapshots.sh
      - name: upload
        run: |
            git config --global user.name "Mobile Automation"
            git config --global user.email "mobile.automation@kiwi.com"
            git commit -am "Updated snapshots."
            git push
